// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmAQGFr2OwpGlKGfoHi6Ync9z63YeqJ4o',
    appId: '1:74386935411:web:a485b9f3968ab5812d6406',
    messagingSenderId: '74386935411',
    projectId: 'fir-project-4ba32',
    authDomain: 'fir-project-4ba32.firebaseapp.com',
    storageBucket: 'fir-project-4ba32.firebasestorage.app',
    measurementId: 'G-5H5HHK868Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD48SiwRzdFjoM5Z_kwhLM2MEp9DmaYrTI',
    appId: '1:74386935411:android:6703229af8ee99cb2d6406',
    messagingSenderId: '74386935411',
    projectId: 'fir-project-4ba32',
    storageBucket: 'fir-project-4ba32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs1lNCfz4So9YbZA_w9Uo4sfZMf4UeUyM',
    appId: '1:74386935411:ios:5c33e2dad4f3eed02d6406',
    messagingSenderId: '74386935411',
    projectId: 'fir-project-4ba32',
    storageBucket: 'fir-project-4ba32.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs1lNCfz4So9YbZA_w9Uo4sfZMf4UeUyM',
    appId: '1:74386935411:ios:5c33e2dad4f3eed02d6406',
    messagingSenderId: '74386935411',
    projectId: 'fir-project-4ba32',
    storageBucket: 'fir-project-4ba32.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmAQGFr2OwpGlKGfoHi6Ync9z63YeqJ4o',
    appId: '1:74386935411:web:98441f19b2b161e32d6406',
    messagingSenderId: '74386935411',
    projectId: 'fir-project-4ba32',
    authDomain: 'fir-project-4ba32.firebaseapp.com',
    storageBucket: 'fir-project-4ba32.firebasestorage.app',
    measurementId: 'G-DMQG6Q6Q71',
  );
}
